### ISSUE TITLE
Mensaje de error poco amigable si se introducen valores de payoffs numéricos directamente

### ISSUE THREAD

**Issue by luis-r-izquierdo** [jba0040/PlataformaTorneos2x2#104]
![screen shot 2017-01-19 at 10 58 30](https://cloud.githubusercontent.com/assets/7665029/22102285/312e5f98-de37-11e6-8867-bea32b840b35.png)

**Comment by JoseBarbero** [comment]
Hola, gracias por la notificación del bug. 
Ya está solucionado, se debía a que no se había tenido en cuenta el carácter especial «'» utilizado en el nombre del torneo. Se tendrá en cuenta para otros apartados de la aplicación.
Un saludo.

**Comment by luis-r-izquierdo** [comment]
Excelente respuesta. No me sorprende después de leer tu TFG. Mucha suerte mañana, aunque creo que no la necesitas

**Comment by clopezno** [comment]
Buena jugada equipo.
